export const stocks = [
    { stockSymbol: "AAPL", stockName: "Apple Inc.", avgTradePrice: 175.25},
    { stockSymbol: "MSFT", stockName: "Microsoft Corporation", avgTradePrice: 342.15 },
    { stockSymbol: "GOOGL", stockName: "Alphabet Inc.", avgTradePrice: 132.45 },
    { stockSymbol: "AMZN", stockName: "Amazon.com Inc.", avgTradePrice: 145.30 },
    { stockSymbol: "TSLA", stockName: "Tesla Inc.", avgTradePrice: 250.50 },
    { stockSymbol: "FB", stockName: "Meta Platforms Inc.", avgTradePrice: 300.20 },
    { stockSymbol: "NFLX", stockName: "Netflix Inc.", avgTradePrice: 450.10 },
    { stockSymbol: "NVDA", stockName: "NVIDIA Corporation", avgTradePrice: 475.00 },
    { stockSymbol: "BRK.B", stockName: "Berkshire Hathaway Inc.", avgTradePrice: 350.75 },
    { stockSymbol: "JPM", stockName: "JPMorgan Chase & Co.", avgTradePrice: 140.25 },
    { stockSymbol: "V", stockName: "Visa Inc.", avgTradePrice: 230.15 },
    { stockSymbol: "MA", stockName: "Mastercard Incorporated", avgTradePrice: 390.50 },
    { stockSymbol: "DIS", stockName: "The Walt Disney Company", avgTradePrice: 120.00 },
    { stockSymbol: "PYPL", stockName: "PayPal Holdings Inc.", avgTradePrice: 75.20 },
    { stockSymbol: "ADBE", stockName: "Adobe Inc.", avgTradePrice: 560.30 },
    { stockSymbol: "CMCSA", stockName: "Comcast Corporation", avgTradePrice: 42.50 },
    { stockSymbol: "INTC", stockName: "Intel Corporation", avgTradePrice: 30.75 },
    { stockSymbol: "CSCO", stockName: "Cisco Systems Inc.", avgTradePrice: 52.10 },
    { stockSymbol: "PEP", stockName: "PepsiCo Inc.", avgTradePrice: 180.00 },
    { stockSymbol: "KO", stockName: "Coca-Cola Company", avgTradePrice: 60.25 },
    { stockSymbol: "PFE", stockName: "Pfizer Inc.", avgTradePrice: 45.00 },
    { stockSymbol: "MRK", stockName: "Merck & Co., Inc.", avgTradePrice: 90.50 },
    { stockSymbol: "ABT", stockName: "Abbott Laboratories", avgTradePrice: 110.20 },
    { stockSymbol: "NKE", stockName: "Nike Inc.", avgTradePrice: 120.00 },
    { stockSymbol: "T", stockName: "AT&T Inc.", avgTradePrice: 15.75 },
    { stockSymbol: "VZ", stockName: "Verizon Communications Inc.", avgTradePrice: 38.50 },
    { stockSymbol: "XOM", stockName: "Exxon Mobil Corporation", avgTradePrice: 105.00 },
    { stockSymbol: "CVX", stockName: "Chevron Corporation", avgTradePrice: 170.25 },
    { stockSymbol: "WMT", stockName: "Walmart Inc.", avgTradePrice: 160.00 },
    { stockSymbol: "HD", stockName: "The Home Depot, Inc.", avgTradePrice: 320.50 },
    { stockSymbol: "UNH", stockName: "UnitedHealth Group Incorporated", avgTradePrice: 490.00 },
    { stockSymbol: "JNJ", stockName: "Johnson & Johnson", avgTradePrice: 155.75 },
    { stockSymbol: "TMO", stockName: "Thermo Fisher Scientific Inc.", avgTradePrice: 600.00 },
    { stockSymbol: "LLY", stockName: "Eli Lilly and Company", avgTradePrice: 450.50 },
    { stockSymbol: "MDT", stockName: "Medtronic plc", avgTradePrice: 90.00 },
    { stockSymbol: "IBM", stockName: "International Business Machines Corporation", avgTradePrice: 140.00 },
    { stockSymbol: "TXN", stockName: "Texas Instruments Incorporated", avgTradePrice: 180.00 },
    { stockSymbol: "QCOM", stockName: "Qualcomm Incorporated", avgTradePrice: 120.75 },
    { stockSymbol: "NOW", stockName: "ServiceNow, Inc.", avgTradePrice: 550.00 },
    { stockSymbol: "CRM", stockName: "Salesforce, Inc.", avgTradePrice: 220.00 },
    { stockSymbol: "SNAP", stockName: "Snap Inc.", avgTradePrice: 10.00 },
    { stockSymbol: "ZM", stockName: "Zoom Video Communications, Inc.", avgTradePrice: 75.00 },
    { stockSymbol: "SPOT", stockName: "Spotify Technology S.A.", avgTradePrice: 150.00 },
    { stockSymbol: "PINS", stockName: "Pinterest, Inc.", avgTradePrice: 25.00 },
    { stockSymbol: "SQ", stockName: "Block, Inc.", avgTradePrice: 70.00 },
    { stockSymbol: "TWTR", stockName: "Twitter, Inc.", avgTradePrice: 45.00 },
    { stockSymbol: "BABA", stockName: "Alibaba Group Holding Limited", avgTradePrice: 85.00 },
    { stockSymbol: "JD", stockName: "JD.com, Inc.", avgTradePrice: 30.00 },
    { stockSymbol: "NIO", stockName: "NIO Inc.", avgTradePrice: 15.00 },
    { stockSymbol: "LI", stockName: "Li Auto Inc.", avgTradePrice: 25.00 },
    { stockSymbol: "XPEV", stockName: "XPeng Inc.", avgTradePrice: 20.00 },
    { stockSymbol: "F", stockName: "Ford Motor Company", avgTradePrice: 12.00 },
    { stockSymbol: "GM", stockName: "General Motors Company", avgTradePrice: 35.00 },
    { stockSymbol: "TSM", stockName: "Taiwan Semiconductor Manufacturing Company", avgTradePrice: 90.00 },
    { stockSymbol: "AVGO", stockName: "Broadcom Inc.", avgTradePrice: 850.00 },
    { stockSymbol: "AMD", stockName: "Advanced Micro Devices, Inc.", avgTradePrice: 105.00 },
    { stockSymbol: "INTU", stockName: "Intuit Inc.", avgTradePrice: 500.00 },
    { stockSymbol: "ATVI", stockName: "Activision Blizzard, Inc.", avgTradePrice: 75.00 },
    { stockSymbol: "EA", stockName: "Electronic Arts Inc.", avgTradePrice: 130.00 },
    { stockSymbol: "LRCX", stockName: "Lam Research Corporation", avgTradePrice: 570.00 },
    { stockSymbol: "AMAT", stockName: "Applied Materials, Inc.", avgTradePrice: 120.00 },
    { stockSymbol: "ADI", stockName: "Analog Devices, Inc.", avgTradePrice: 190.00 },
    { stockSymbol: "MCHP", stockName: "Microchip Technology Incorporated", avgTradePrice: 90.00 },
    { stockSymbol: "NXPI", stockName: "NXP Semiconductors N.V.", avgTradePrice: 190.00 },
    { stockSymbol: "BIDU", stockName: "Baidu, Inc.", avgTradePrice: 140.00 },
    { stockSymbol: "PDD", stockName: "Pinduoduo Inc.", avgTradePrice: 90.00 },
    { stockSymbol: "TCEHY", stockName: "Tencent Holdings Limited", avgTradePrice: 50.00 },
    { stockSymbol: "NTES", stockName: "NetEase, Inc.", avgTradePrice: 80.00 },
    { stockSymbol: "BILI", stockName: "Bilibili Inc.", avgTradePrice: 20.00 },
    { stockSymbol: "HDFCBANK", stockName: "HDFC Bank Limited", avgTradePrice: 65.00 },
    { stockSymbol: "ICLK", stockName: "iClick Interactive Asia Group Limited", avgTradePrice: 15.00 },
    { stockSymbol: "BHP", stockName: "BHP Group", avgTradePrice: 60.00 },
    { stockSymbol: "RIO", stockName: "Rio Tinto Group", avgTradePrice: 70.00 },
    { stockSymbol: "VALE", stockName: "Vale S.A.", avgTradePrice: 15.00 },
    { stockSymbol: "NEM", stockName: "Newmont Corporation", avgTradePrice: 45.00 },
    { stockSymbol: "GOLD", stockName: "Barrick Gold Corporation", avgTradePrice: 18.00 },
    { stockSymbol: "SLV", stockName: "iShares Silver Trust", avgTradePrice: 23.00 },
    { stockSymbol: "SPY", stockName: "SPDR S&P 500 ETF Trust", avgTradePrice: 440.00 },
    { stockSymbol: "QQQ", stockName: "Invesco QQQ Trust", avgTradePrice: 370.00 },
    { stockSymbol: "IWM", stockName: "iShares Russell 2000 ETF", avgTradePrice: 200.00 },
    { stockSymbol: "DIA", stockName: "SPDR Dow Jones Industrial Average ETF Trust", avgTradePrice: 340.00 },
    { stockSymbol: "XLF", stockName: "Financial Select Sector SPDR Fund", avgTradePrice: 36.00 },
    { stockSymbol: "XLY", stockName: "Consumer Discretionary Select Sector SPDR Fund", avgTradePrice: 185.00 },
    { stockSymbol: "XLC", stockName: "Communication Services Select Sector SPDR Fund", avgTradePrice: 60.00 },
    { stockSymbol: "XLI", stockName: "Industrial Select Sector SPDR Fund", avgTradePrice: 105.00 },
    { stockSymbol: "XLB", stockName: "Materials Select Sector SPDR Fund", avgTradePrice: 85.00 },
    { stockSymbol: "HINDUNILVR", stockName: "Hindustan Unilever Ltd", avgTradePrice: 2933 },
    { stockSymbol: "BHARTIARTL", stockName: "Bharti Airtel Ltd", avgTradePrice: 834.50 },
    { stockSymbol: "HDFCBANK", stockName: "HDFC Bank Ltd", avgTradePrice: 1568.50 },
    { stockSymbol: "INFY", stockName: "Infosys Ltd", avgTradePrice: 1470 },
    { stockSymbol: "KPITTECH", stockName: "KPIT Technologies Ltd", avgTradePrice: 800 },
    { stockSymbol: "M&M", stockName: "Mahindra & Mahindra Ltd", avgTradePrice: 1400 },
    { stockSymbol: "RELIANCE", stockName: "Reliance Industries Ltd", avgTradePrice: 2500 },
    { stockSymbol: "SBIN", stockName: "State Bank of India", avgTradePrice: 600 },
    { stockSymbol: "SGBMAY29", stockName: "Sovereign Gold Bond May 2029", avgTradePrice: 5500 },
    { stockSymbol: "TATAPOWER", stockName: "Tata Power Company Ltd", avgTradePrice: 280 },
    { stockSymbol: "TCS", stockName: "Tata Consultancy Services Ltd", avgTradePrice: 3500 },
    { stockSymbol: "WIPRO", stockName: "Wipro Ltd", avgTradePrice: 400 },
    { stockSymbol: "ITC", stockName: "ITC Ltd", avgTradePrice: 500 },
];